/**
 * Provides the classes necessary to marshal and un-marshal TCG integrity 
 * reports. The source and classes are generated by the xjc tool, integrity 
 * report schema, and binding document.
 *
 * @version Crossbow
 */
package gov.niarl.his.xsd;

