//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 03:47:01 PM EDT 
//


package gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.integrity_Report_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CapVersionInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CapVersionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Tag" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="VersionMajor" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="VersionMinor" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="VersionRevMajor" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="VersionRevMinor" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="SpecLevel" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="ErrataRev" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="TpmVendorID" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="VendorSpecificSize" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="VendorSpecific" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CapVersionInfoType")
public class CapVersionInfoType {

    @XmlAttribute(name = "Tag", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int tag;
    @XmlAttribute(name = "VersionMajor", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short versionMajor;
    @XmlAttribute(name = "VersionMinor", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short versionMinor;
    @XmlAttribute(name = "VersionRevMajor", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short versionRevMajor;
    @XmlAttribute(name = "VersionRevMinor", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short versionRevMinor;
    @XmlAttribute(name = "SpecLevel", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int specLevel;
    @XmlAttribute(name = "ErrataRev", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short errataRev;
    @XmlAttribute(name = "TpmVendorID", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String tpmVendorID;
    @XmlAttribute(name = "VendorSpecificSize", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int vendorSpecificSize;
    @XmlAttribute(name = "VendorSpecific")
    protected byte[] vendorSpecific;

    /**
     * Gets the value of the tag property.
     * 
     */
    public int getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     */
    public void setTag(int value) {
        this.tag = value;
    }

    /**
     * Gets the value of the versionMajor property.
     * 
     */
    public short getVersionMajor() {
        return versionMajor;
    }

    /**
     * Sets the value of the versionMajor property.
     * 
     */
    public void setVersionMajor(short value) {
        this.versionMajor = value;
    }

    /**
     * Gets the value of the versionMinor property.
     * 
     */
    public short getVersionMinor() {
        return versionMinor;
    }

    /**
     * Sets the value of the versionMinor property.
     * 
     */
    public void setVersionMinor(short value) {
        this.versionMinor = value;
    }

    /**
     * Gets the value of the versionRevMajor property.
     * 
     */
    public short getVersionRevMajor() {
        return versionRevMajor;
    }

    /**
     * Sets the value of the versionRevMajor property.
     * 
     */
    public void setVersionRevMajor(short value) {
        this.versionRevMajor = value;
    }

    /**
     * Gets the value of the versionRevMinor property.
     * 
     */
    public short getVersionRevMinor() {
        return versionRevMinor;
    }

    /**
     * Sets the value of the versionRevMinor property.
     * 
     */
    public void setVersionRevMinor(short value) {
        this.versionRevMinor = value;
    }

    /**
     * Gets the value of the specLevel property.
     * 
     */
    public int getSpecLevel() {
        return specLevel;
    }

    /**
     * Sets the value of the specLevel property.
     * 
     */
    public void setSpecLevel(int value) {
        this.specLevel = value;
    }

    /**
     * Gets the value of the errataRev property.
     * 
     */
    public short getErrataRev() {
        return errataRev;
    }

    /**
     * Sets the value of the errataRev property.
     * 
     */
    public void setErrataRev(short value) {
        this.errataRev = value;
    }

    /**
     * Gets the value of the tpmVendorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpmVendorID() {
        return tpmVendorID;
    }

    /**
     * Sets the value of the tpmVendorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpmVendorID(String value) {
        this.tpmVendorID = value;
    }

    /**
     * Gets the value of the vendorSpecificSize property.
     * 
     */
    public int getVendorSpecificSize() {
        return vendorSpecificSize;
    }

    /**
     * Sets the value of the vendorSpecificSize property.
     * 
     */
    public void setVendorSpecificSize(int value) {
        this.vendorSpecificSize = value;
    }

    /**
     * Gets the value of the vendorSpecific property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getVendorSpecific() {
        return vendorSpecific;
    }

    /**
     * Sets the value of the vendorSpecific property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setVendorSpecific(byte[] value) {
        this.vendorSpecific = ((byte[]) value);
    }

}
