//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 03:47:01 PM EDT 
//


package gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.integrity_Report_v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.integrity_Report_v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Snapshot_QNAME = new QName("http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#", "Snapshot");
    private final static QName _Report_QNAME = new QName("http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#", "Report");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.integrity_Report_v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QuoteSignatureType }
     * 
     */
    public QuoteSignatureType createQuoteSignatureType() {
        return new QuoteSignatureType();
    }

    /**
     * Create an instance of {@link QuoteInfoType }
     * 
     */
    public QuoteInfoType createQuoteInfoType() {
        return new QuoteInfoType();
    }

    /**
     * Create an instance of {@link CapVersionInfoType }
     * 
     */
    public CapVersionInfoType createCapVersionInfoType() {
        return new CapVersionInfoType();
    }

    /**
     * Create an instance of {@link CompositeHashType }
     * 
     */
    public CompositeHashType createCompositeHashType() {
        return new CompositeHashType();
    }

    /**
     * Create an instance of {@link QuoteDataType }
     * 
     */
    public QuoteDataType createQuoteDataType() {
        return new QuoteDataType();
    }

    /**
     * Create an instance of {@link QuoteInfo2Type }
     * 
     */
    public QuoteInfo2Type createQuoteInfo2Type() {
        return new QuoteInfo2Type();
    }

    /**
     * Create an instance of {@link PcrCompositeType.PcrValue }
     * 
     */
    public PcrCompositeType.PcrValue createPcrCompositeTypePcrValue() {
        return new PcrCompositeType.PcrValue();
    }

    /**
     * Create an instance of {@link Quote2Type }
     * 
     */
    public Quote2Type createQuote2Type() {
        return new Quote2Type();
    }

    /**
     * Create an instance of {@link QuoteType.TpmInfo }
     * 
     */
    public QuoteType.TpmInfo createQuoteTypeTpmInfo() {
        return new QuoteType.TpmInfo();
    }

    /**
     * Create an instance of {@link PcrInfoShortType }
     * 
     */
    public PcrInfoShortType createPcrInfoShortType() {
        return new PcrInfoShortType();
    }

    /**
     * Create an instance of {@link ReportType }
     * 
     */
    public ReportType createReportType() {
        return new ReportType();
    }

    /**
     * Create an instance of {@link PcrSelectionType }
     * 
     */
    public PcrSelectionType createPcrSelectionType() {
        return new PcrSelectionType();
    }

    /**
     * Create an instance of {@link SnapshotType }
     * 
     */
    public SnapshotType createSnapshotType() {
        return new SnapshotType();
    }

    /**
     * Create an instance of {@link QuoteType }
     * 
     */
    public QuoteType createQuoteType() {
        return new QuoteType();
    }

    /**
     * Create an instance of {@link PcrCompositeType }
     * 
     */
    public PcrCompositeType createPcrCompositeType() {
        return new PcrCompositeType();
    }

    /**
     * Create an instance of {@link TpmDigestValueType }
     * 
     */
    public TpmDigestValueType createTpmDigestValueType() {
        return new TpmDigestValueType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SnapshotType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#", name = "Snapshot")
    public JAXBElement<SnapshotType> createSnapshot(SnapshotType value) {
        return new JAXBElement<SnapshotType>(_Snapshot_QNAME, SnapshotType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#", name = "Report")
    public JAXBElement<ReportType> createReport(ReportType value) {
        return new JAXBElement<ReportType>(_Report_QNAME, ReportType.class, null, value);
    }

}
