//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 03:47:01 PM EDT 
//


package gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.integrity_Report_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PcrInfoShortType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PcrInfoShortType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PcrSelection" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}PcrSelectionType"/>
 *         &lt;element name="LocalityAtRelease" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="CompositeHash" type="{http://www.w3.org/2000/09/xmldsig#}DigestValueType"/>
 *         &lt;element name="PcrComposite" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}PcrCompositeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PcrInfoShortType", propOrder = {
    "pcrSelection",
    "localityAtRelease",
    "compositeHash",
    "pcrComposite"
})
public class PcrInfoShortType {

    @XmlElement(name = "PcrSelection", required = true)
    protected PcrSelectionType pcrSelection;
    @XmlElement(name = "LocalityAtRelease")
    @XmlSchemaType(name = "unsignedByte")
    protected short localityAtRelease;
    @XmlElement(name = "CompositeHash", required = true)
    protected byte[] compositeHash;
    @XmlElement(name = "PcrComposite", required = true)
    protected PcrCompositeType pcrComposite;

    /**
     * Gets the value of the pcrSelection property.
     * 
     * @return
     *     possible object is
     *     {@link PcrSelectionType }
     *     
     */
    public PcrSelectionType getPcrSelection() {
        return pcrSelection;
    }

    /**
     * Sets the value of the pcrSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link PcrSelectionType }
     *     
     */
    public void setPcrSelection(PcrSelectionType value) {
        this.pcrSelection = value;
    }

    /**
     * Gets the value of the localityAtRelease property.
     * 
     */
    public short getLocalityAtRelease() {
        return localityAtRelease;
    }

    /**
     * Sets the value of the localityAtRelease property.
     * 
     */
    public void setLocalityAtRelease(short value) {
        this.localityAtRelease = value;
    }

    /**
     * Gets the value of the compositeHash property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCompositeHash() {
        return compositeHash;
    }

    /**
     * Sets the value of the compositeHash property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCompositeHash(byte[] value) {
        this.compositeHash = ((byte[]) value);
    }

    /**
     * Gets the value of the pcrComposite property.
     * 
     * @return
     *     possible object is
     *     {@link PcrCompositeType }
     *     
     */
    public PcrCompositeType getPcrComposite() {
        return pcrComposite;
    }

    /**
     * Sets the value of the pcrComposite property.
     * 
     * @param value
     *     allowed object is
     *     {@link PcrCompositeType }
     *     
     */
    public void setPcrComposite(PcrCompositeType value) {
        this.pcrComposite = value;
    }

}
