//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 03:47:01 PM EDT 
//


package gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.integrity_Report_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for QuoteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuoteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PcrComposite" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}PcrCompositeType"/>
 *         &lt;element name="QuoteInfo" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}QuoteInfoType"/>
 *         &lt;element name="TpmInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="CapVersionInfo" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}CapVersionInfoType"/>
 *                   &lt;element name="TpmManufacturer" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuoteType", propOrder = {
    "pcrComposite",
    "quoteInfo",
    "tpmInfo"
})
public class QuoteType {

    @XmlElement(name = "PcrComposite", required = true)
    protected PcrCompositeType pcrComposite;
    @XmlElement(name = "QuoteInfo", required = true)
    protected QuoteInfoType quoteInfo;
    @XmlElement(name = "TpmInfo")
    protected QuoteType.TpmInfo tpmInfo;

    /**
     * Gets the value of the pcrComposite property.
     * 
     * @return
     *     possible object is
     *     {@link PcrCompositeType }
     *     
     */
    public PcrCompositeType getPcrComposite() {
        return pcrComposite;
    }

    /**
     * Sets the value of the pcrComposite property.
     * 
     * @param value
     *     allowed object is
     *     {@link PcrCompositeType }
     *     
     */
    public void setPcrComposite(PcrCompositeType value) {
        this.pcrComposite = value;
    }

    /**
     * Gets the value of the quoteInfo property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteInfoType }
     *     
     */
    public QuoteInfoType getQuoteInfo() {
        return quoteInfo;
    }

    /**
     * Sets the value of the quoteInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteInfoType }
     *     
     */
    public void setQuoteInfo(QuoteInfoType value) {
        this.quoteInfo = value;
    }

    /**
     * Gets the value of the tpmInfo property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteType.TpmInfo }
     *     
     */
    public QuoteType.TpmInfo getTpmInfo() {
        return tpmInfo;
    }

    /**
     * Sets the value of the tpmInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteType.TpmInfo }
     *     
     */
    public void setTpmInfo(QuoteType.TpmInfo value) {
        this.tpmInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="CapVersionInfo" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}CapVersionInfoType"/>
     *         &lt;element name="TpmManufacturer" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "capVersionInfo",
        "tpmManufacturer"
    })
    public static class TpmInfo {

        @XmlElement(name = "CapVersionInfo")
        protected CapVersionInfoType capVersionInfo;
        @XmlElement(name = "TpmManufacturer")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String tpmManufacturer;

        /**
         * Gets the value of the capVersionInfo property.
         * 
         * @return
         *     possible object is
         *     {@link CapVersionInfoType }
         *     
         */
        public CapVersionInfoType getCapVersionInfo() {
            return capVersionInfo;
        }

        /**
         * Sets the value of the capVersionInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link CapVersionInfoType }
         *     
         */
        public void setCapVersionInfo(CapVersionInfoType value) {
            this.capVersionInfo = value;
        }

        /**
         * Gets the value of the tpmManufacturer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTpmManufacturer() {
            return tpmManufacturer;
        }

        /**
         * Sets the value of the tpmManufacturer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTpmManufacturer(String value) {
            this.tpmManufacturer = value;
        }

    }

}
