//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.28 at 01:24:35 PM EDT 
//


package org.trustedcomputinggroup.xml.schema.integrity_report_v1_0_;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for PcrCompositeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PcrCompositeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PcrSelection" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}PcrSelectionType"/>
 *         &lt;element name="ValueSize" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="PcrValue" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2000/09/xmldsig#>DigestValueType">
 *                 &lt;attribute name="SnapshotRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                 &lt;attribute name="PcrNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PcrCompositeType", propOrder = {
    "pcrSelection",
    "valueSize",
    "pcrValue"
})
public class PcrCompositeType {

    @XmlElement(name = "PcrSelection", required = true)
    protected PcrSelectionType pcrSelection;
    @XmlElement(name = "ValueSize", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger valueSize;
    @XmlElement(name = "PcrValue", required = true)
    protected List<PcrCompositeType.PcrValue> pcrValue;

    /**
     * Gets the value of the pcrSelection property.
     * 
     * @return
     *     possible object is
     *     {@link PcrSelectionType }
     *     
     */
    public PcrSelectionType getPcrSelection() {
        return pcrSelection;
    }

    /**
     * Sets the value of the pcrSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link PcrSelectionType }
     *     
     */
    public void setPcrSelection(PcrSelectionType value) {
        this.pcrSelection = value;
    }

    /**
     * Gets the value of the valueSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValueSize() {
        return valueSize;
    }

    /**
     * Sets the value of the valueSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setValueSize(BigInteger value) {
        this.valueSize = value;
    }

    /**
     * Gets the value of the pcrValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pcrValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPcrValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PcrCompositeType.PcrValue }
     * 
     * 
     */
    public List<PcrCompositeType.PcrValue> getPcrValue() {
        if (pcrValue == null) {
            pcrValue = new ArrayList<PcrCompositeType.PcrValue>();
        }
        return this.pcrValue;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2000/09/xmldsig#>DigestValueType">
     *       &lt;attribute name="SnapshotRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *       &lt;attribute name="PcrNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PcrValue {

        @XmlValue
        protected byte[] value;
        @XmlAttribute(name = "SnapshotRef")
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object snapshotRef;
        @XmlAttribute(name = "PcrNumber", required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger pcrNumber;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setValue(byte[] value) {
            this.value = ((byte[]) value);
        }

        /**
         * Gets the value of the snapshotRef property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getSnapshotRef() {
            return snapshotRef;
        }

        /**
         * Sets the value of the snapshotRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setSnapshotRef(Object value) {
            this.snapshotRef = value;
        }

        /**
         * Gets the value of the pcrNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPcrNumber() {
            return pcrNumber;
        }

        /**
         * Sets the value of the pcrNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPcrNumber(BigInteger value) {
            this.pcrNumber = value;
        }

    }

}
