//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.28 at 01:24:35 PM EDT 
//


package org.trustedcomputinggroup.xml.schema.integrity_report_v1_0_;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PcrSelectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PcrSelectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="SizeOfSelect" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="PcrSelect" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PcrSelectionType")
public class PcrSelectionType {

    @XmlAttribute(name = "SizeOfSelect", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int sizeOfSelect;
    @XmlAttribute(name = "PcrSelect", required = true)
    protected byte[] pcrSelect;

    /**
     * Gets the value of the sizeOfSelect property.
     * 
     */
    public int getSizeOfSelect() {
        return sizeOfSelect;
    }

    /**
     * Sets the value of the sizeOfSelect property.
     * 
     */
    public void setSizeOfSelect(int value) {
        this.sizeOfSelect = value;
    }

    /**
     * Gets the value of the pcrSelect property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPcrSelect() {
        return pcrSelect;
    }

    /**
     * Sets the value of the pcrSelect property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPcrSelect(byte[] value) {
        this.pcrSelect = ((byte[]) value);
    }

}
