//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.28 at 01:24:35 PM EDT 
//


package org.trustedcomputinggroup.xml.schema.integrity_report_v1_0_;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for QuoteInfo2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuoteInfo2Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PcrInfoShort" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}PcrInfoShortType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Tag" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="Fixed" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="ExternalData" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuoteInfo2Type", propOrder = {
    "pcrInfoShort"
})
public class QuoteInfo2Type {

    @XmlElement(name = "PcrInfoShort", required = true)
    protected PcrInfoShortType pcrInfoShort;
    @XmlAttribute(name = "Tag", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int tag;
    @XmlAttribute(name = "Fixed", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String fixed;
    @XmlAttribute(name = "ExternalData", required = true)
    protected byte[] externalData;

    /**
     * Gets the value of the pcrInfoShort property.
     * 
     * @return
     *     possible object is
     *     {@link PcrInfoShortType }
     *     
     */
    public PcrInfoShortType getPcrInfoShort() {
        return pcrInfoShort;
    }

    /**
     * Sets the value of the pcrInfoShort property.
     * 
     * @param value
     *     allowed object is
     *     {@link PcrInfoShortType }
     *     
     */
    public void setPcrInfoShort(PcrInfoShortType value) {
        this.pcrInfoShort = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     */
    public int getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     */
    public void setTag(int value) {
        this.tag = value;
    }

    /**
     * Gets the value of the fixed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixed() {
        return fixed;
    }

    /**
     * Sets the value of the fixed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixed(String value) {
        this.fixed = value;
    }

    /**
     * Gets the value of the externalData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getExternalData() {
        return externalData;
    }

    /**
     * Sets the value of the externalData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setExternalData(byte[] value) {
        this.externalData = ((byte[]) value);
    }

}
