//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.28 at 01:24:35 PM EDT 
//


package org.trustedcomputinggroup.xml.schema.integrity_report_v1_0_;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for QuoteDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuoteDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="Quote" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}QuoteType"/>
 *           &lt;element name="Quote2" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}Quote2Type"/>
 *         &lt;/choice>
 *         &lt;element name="TpmSignature" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}QuoteSignatureType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuoteDataType", propOrder = {
    "quote",
    "quote2",
    "tpmSignature"
})
public class QuoteDataType {

    @XmlElement(name = "Quote")
    protected QuoteType quote;
    @XmlElement(name = "Quote2")
    protected Quote2Type quote2;
    @XmlElement(name = "TpmSignature", required = true)
    protected QuoteSignatureType tpmSignature;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the quote property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteType }
     *     
     */
    public QuoteType getQuote() {
        return quote;
    }

    /**
     * Sets the value of the quote property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteType }
     *     
     */
    public void setQuote(QuoteType value) {
        this.quote = value;
    }

    /**
     * Gets the value of the quote2 property.
     * 
     * @return
     *     possible object is
     *     {@link Quote2Type }
     *     
     */
    public Quote2Type getQuote2() {
        return quote2;
    }

    /**
     * Sets the value of the quote2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quote2Type }
     *     
     */
    public void setQuote2(Quote2Type value) {
        this.quote2 = value;
    }

    /**
     * Gets the value of the tpmSignature property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteSignatureType }
     *     
     */
    public QuoteSignatureType getTpmSignature() {
        return tpmSignature;
    }

    /**
     * Sets the value of the tpmSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteSignatureType }
     *     
     */
    public void setTpmSignature(QuoteSignatureType value) {
        this.tpmSignature = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
