//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.28 at 01:24:35 PM EDT 
//


package org.trustedcomputinggroup.xml.schema.integrity_report_v1_0_;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Quote2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Quote2Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QuoteInfo2" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}QuoteInfo2Type"/>
 *         &lt;element name="CapVersionInfo" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Integrity_Report_v1_0#}CapVersionInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Quote2Type", propOrder = {
    "quoteInfo2",
    "capVersionInfo"
})
public class Quote2Type {

    @XmlElement(name = "QuoteInfo2", required = true)
    protected QuoteInfo2Type quoteInfo2;
    @XmlElement(name = "CapVersionInfo")
    protected CapVersionInfoType capVersionInfo;

    /**
     * Gets the value of the quoteInfo2 property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteInfo2Type }
     *     
     */
    public QuoteInfo2Type getQuoteInfo2() {
        return quoteInfo2;
    }

    /**
     * Sets the value of the quoteInfo2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteInfo2Type }
     *     
     */
    public void setQuoteInfo2(QuoteInfo2Type value) {
        this.quoteInfo2 = value;
    }

    /**
     * Gets the value of the capVersionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CapVersionInfoType }
     *     
     */
    public CapVersionInfoType getCapVersionInfo() {
        return capVersionInfo;
    }

    /**
     * Sets the value of the capVersionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapVersionInfoType }
     *     
     */
    public void setCapVersionInfo(CapVersionInfoType value) {
        this.capVersionInfo = value;
    }

}
