//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.28 at 01:24:35 PM EDT 
//


package org.trustedcomputinggroup.xml.schema.integrity_report_v1_0_;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for QuoteInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuoteInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="VersionMajor" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="VersionMinor" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="VersionRevMajor" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="VersionRevMinor" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="Fixed" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="DigestValue" use="required" type="{http://www.w3.org/2000/09/xmldsig#}DigestValueType" />
 *       &lt;attribute name="ExternalData" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuoteInfoType")
public class QuoteInfoType {

    @XmlAttribute(name = "VersionMajor", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short versionMajor;
    @XmlAttribute(name = "VersionMinor", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short versionMinor;
    @XmlAttribute(name = "VersionRevMajor", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short versionRevMajor;
    @XmlAttribute(name = "VersionRevMinor", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short versionRevMinor;
    @XmlAttribute(name = "Fixed", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String fixed;
    @XmlAttribute(name = "DigestValue", required = true)
    protected byte[] digestValue;
    @XmlAttribute(name = "ExternalData", required = true)
    protected byte[] externalData;

    /**
     * Gets the value of the versionMajor property.
     * 
     */
    public short getVersionMajor() {
        return versionMajor;
    }

    /**
     * Sets the value of the versionMajor property.
     * 
     */
    public void setVersionMajor(short value) {
        this.versionMajor = value;
    }

    /**
     * Gets the value of the versionMinor property.
     * 
     */
    public short getVersionMinor() {
        return versionMinor;
    }

    /**
     * Sets the value of the versionMinor property.
     * 
     */
    public void setVersionMinor(short value) {
        this.versionMinor = value;
    }

    /**
     * Gets the value of the versionRevMajor property.
     * 
     */
    public short getVersionRevMajor() {
        return versionRevMajor;
    }

    /**
     * Sets the value of the versionRevMajor property.
     * 
     */
    public void setVersionRevMajor(short value) {
        this.versionRevMajor = value;
    }

    /**
     * Gets the value of the versionRevMinor property.
     * 
     */
    public short getVersionRevMinor() {
        return versionRevMinor;
    }

    /**
     * Sets the value of the versionRevMinor property.
     * 
     */
    public void setVersionRevMinor(short value) {
        this.versionRevMinor = value;
    }

    /**
     * Gets the value of the fixed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixed() {
        return fixed;
    }

    /**
     * Sets the value of the fixed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixed(String value) {
        this.fixed = value;
    }

    /**
     * Gets the value of the digestValue property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDigestValue() {
        return digestValue;
    }

    /**
     * Sets the value of the digestValue property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setDigestValue(byte[] value) {
        this.digestValue = ((byte[]) value);
    }

    /**
     * Gets the value of the externalData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getExternalData() {
        return externalData;
    }

    /**
     * Sets the value of the externalData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setExternalData(byte[] value) {
        this.externalData = ((byte[]) value);
    }

}
