//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.28 at 01:24:35 PM EDT 
//


package org.trustedcomputinggroup.xml.schema.integrity_report_v1_0_;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.trustedcomputinggroup.xml.schema.core_integrity_v1_0_1_.HashType;


/**
 * <p>Java class for TpmDigestValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TpmDigestValueType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#>HashType">
 *       &lt;attribute name="Locality" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="IsResetable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="StartHash" use="required" type="{http://www.w3.org/2000/09/xmldsig#}DigestValueType" />
 *       &lt;attribute name="SyncRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TpmDigestValueType")
public class TpmDigestValueType
    extends HashType
{

    @XmlAttribute(name = "Locality")
    protected BigInteger locality;
    @XmlAttribute(name = "IsResetable", required = true)
    protected boolean isResetable;
    @XmlAttribute(name = "Name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String name;
    @XmlAttribute(name = "Number")
    protected BigInteger number;
    @XmlAttribute(name = "StartHash", required = true)
    protected byte[] startHash;
    @XmlAttribute(name = "SyncRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object syncRef;
    @XmlAttribute(name = "Timestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;

    /**
     * Gets the value of the locality property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocality() {
        return locality;
    }

    /**
     * Sets the value of the locality property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocality(BigInteger value) {
        this.locality = value;
    }

    /**
     * Gets the value of the isResetable property.
     * 
     */
    public boolean isIsResetable() {
        return isResetable;
    }

    /**
     * Sets the value of the isResetable property.
     * 
     */
    public void setIsResetable(boolean value) {
        this.isResetable = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

    /**
     * Gets the value of the startHash property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getStartHash() {
        return startHash;
    }

    /**
     * Sets the value of the startHash property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setStartHash(byte[] value) {
        this.startHash = ((byte[]) value);
    }

    /**
     * Gets the value of the syncRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSyncRef() {
        return syncRef;
    }

    /**
     * Sets the value of the syncRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSyncRef(Object value) {
        this.syncRef = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

}
