//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.24 at 08:52:43 PM EDT 
//


package gov.niarl.his.xsd.pcr_difference;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.niarl.his.xsd.pcr_difference package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.niarl.his.xsd.pcr_difference
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PCRDifferenceReport.PreviousValue }
     * 
     */
    public PCRDifferenceReport.PreviousValue createPCRDifferenceReportPreviousValue() {
        return new PCRDifferenceReport.PreviousValue();
    }

    /**
     * Create an instance of {@link PCRDifferenceReport }
     * 
     */
    public PCRDifferenceReport createPCRDifferenceReport() {
        return new PCRDifferenceReport();
    }

    /**
     * Create an instance of {@link PCRDifferenceReport.PreviousCurrent }
     * 
     */
    public PCRDifferenceReport.PreviousCurrent createPCRDifferenceReportPreviousCurrent() {
        return new PCRDifferenceReport.PreviousCurrent();
    }

    /**
     * Create an instance of {@link PCRDifferenceReport.CurrentValue }
     * 
     */
    public PCRDifferenceReport.CurrentValue createPCRDifferenceReportCurrentValue() {
        return new PCRDifferenceReport.CurrentValue();
    }

}
