//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.24 at 08:52:43 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:gov:niarl:his:xsd:pcr_difference", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.niarl.his.xsd.pcr_difference;
