//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.24 at 08:52:43 PM EDT 
//


package gov.niarl.his.xsd.pcr_difference;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Machine_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PCR_Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PCR_Number" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Previous_Value">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Report_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Current_Value">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Report_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Previous_Current">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "machineName",
    "pcrDescription",
    "pcrNumber",
    "previousValue",
    "currentValue",
    "previousCurrent"
})
@XmlRootElement(name = "PCR_Difference_Report")
public class PCRDifferenceReport {

    @XmlElement(name = "Machine_Name", required = true)
    protected String machineName;
    @XmlElement(name = "PCR_Description", required = true)
    protected String pcrDescription;
    @XmlElement(name = "PCR_Number", required = true)
    protected BigInteger pcrNumber;
    @XmlElement(name = "Previous_Value", required = true)
    protected PCRDifferenceReport.PreviousValue previousValue;
    @XmlElement(name = "Current_Value", required = true)
    protected PCRDifferenceReport.CurrentValue currentValue;
    @XmlElement(name = "Previous_Current", required = true)
    protected PCRDifferenceReport.PreviousCurrent previousCurrent;

    /**
     * Gets the value of the machineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMachineName() {
        return machineName;
    }

    /**
     * Sets the value of the machineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMachineName(String value) {
        this.machineName = value;
    }

    /**
     * Gets the value of the pcrDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCRDescription() {
        return pcrDescription;
    }

    /**
     * Sets the value of the pcrDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCRDescription(String value) {
        this.pcrDescription = value;
    }

    /**
     * Gets the value of the pcrNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPCRNumber() {
        return pcrNumber;
    }

    /**
     * Sets the value of the pcrNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPCRNumber(BigInteger value) {
        this.pcrNumber = value;
    }

    /**
     * Gets the value of the previousValue property.
     * 
     * @return
     *     possible object is
     *     {@link PCRDifferenceReport.PreviousValue }
     *     
     */
    public PCRDifferenceReport.PreviousValue getPreviousValue() {
        return previousValue;
    }

    /**
     * Sets the value of the previousValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link PCRDifferenceReport.PreviousValue }
     *     
     */
    public void setPreviousValue(PCRDifferenceReport.PreviousValue value) {
        this.previousValue = value;
    }

    /**
     * Gets the value of the currentValue property.
     * 
     * @return
     *     possible object is
     *     {@link PCRDifferenceReport.CurrentValue }
     *     
     */
    public PCRDifferenceReport.CurrentValue getCurrentValue() {
        return currentValue;
    }

    /**
     * Sets the value of the currentValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link PCRDifferenceReport.CurrentValue }
     *     
     */
    public void setCurrentValue(PCRDifferenceReport.CurrentValue value) {
        this.currentValue = value;
    }

    /**
     * Gets the value of the previousCurrent property.
     * 
     * @return
     *     possible object is
     *     {@link PCRDifferenceReport.PreviousCurrent }
     *     
     */
    public PCRDifferenceReport.PreviousCurrent getPreviousCurrent() {
        return previousCurrent;
    }

    /**
     * Sets the value of the previousCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PCRDifferenceReport.PreviousCurrent }
     *     
     */
    public void setPreviousCurrent(PCRDifferenceReport.PreviousCurrent value) {
        this.previousCurrent = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Report_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CurrentValue {

        @XmlAttribute(name = "Report_ID")
        protected String reportID;
        @XmlAttribute(name = "Timestamp")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timestamp;
        @XmlAttribute(name = "Value")
        protected String value;

        /**
         * Gets the value of the reportID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportID() {
            return reportID;
        }

        /**
         * Sets the value of the reportID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportID(String value) {
            this.reportID = value;
        }

        /**
         * Gets the value of the timestamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimestamp() {
            return timestamp;
        }

        /**
         * Sets the value of the timestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimestamp(XMLGregorianCalendar value) {
            this.timestamp = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PreviousCurrent {

        @XmlElement(name = "Value")
        protected List<String> value;

        /**
         * Gets the value of the value property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getValue() {
            if (value == null) {
                value = new ArrayList<String>();
            }
            return this.value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Report_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PreviousValue {

        @XmlAttribute(name = "Report_ID")
        protected String reportID;
        @XmlAttribute(name = "Timestamp")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timestamp;
        @XmlAttribute(name = "Value")
        protected String value;

        /**
         * Gets the value of the reportID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportID() {
            return reportID;
        }

        /**
         * Sets the value of the reportID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportID(String value) {
            this.reportID = value;
        }

        /**
         * Gets the value of the timestamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimestamp() {
            return timestamp;
        }

        /**
         * Sets the value of the timestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimestamp(XMLGregorianCalendar value) {
            this.timestamp = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
