//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.28 at 01:24:35 PM EDT 
//


package org.trustedcomputinggroup.xml.schema.core_integrity_v1_0_1_;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.trustedcomputinggroup.xml.schema.integrity_report_v1_0_.CompositeHashType;
import org.trustedcomputinggroup.xml.schema.integrity_report_v1_0_.TpmDigestValueType;


/**
 * <p>Java class for HashType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HashType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#>DigestValueType">
 *       &lt;attribute name="ExtendOrder" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HashType")
@XmlSeeAlso({
    CompositeHashType.class,
    TpmDigestValueType.class
})
public class HashType
    extends DigestValueType
{

    @XmlAttribute(name = "ExtendOrder")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> extendOrder;

    /**
     * Gets the value of the extendOrder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extendOrder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtendOrder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getExtendOrder() {
        if (extendOrder == null) {
            extendOrder = new ArrayList<Object>();
        }
        return this.extendOrder;
    }

}
