//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.28 at 01:24:35 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.trustedcomputinggroup.xml.schema.core_integrity_v1_0_1_;
