//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 03:47:01 PM EDT 
//


package gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.core_Integrity_v1_0_1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ComponentIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComponentIDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VendorID" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#}VendorIdType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="SimpleName" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="ModelName" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="ModelNumber" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="ModelSerialNumber" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="ModelSystemClass" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="VersionMajor" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="VersionMinor" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="VersionBuild" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="VersionString" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="MfgDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="PatchLevel" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="DiscretePatches" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentIDType", propOrder = {
    "vendorID"
})
@XmlSeeAlso({
    gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.core_Integrity_v1_0_1.ComponentRefType.ComponentID.class
})
public class ComponentIDType {

    @XmlElement(name = "VendorID", required = true)
    protected VendorIdType vendorID;
    @XmlAttribute(name = "Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "SimpleName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String simpleName;
    @XmlAttribute(name = "ModelName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String modelName;
    @XmlAttribute(name = "ModelNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String modelNumber;
    @XmlAttribute(name = "ModelSerialNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String modelSerialNumber;
    @XmlAttribute(name = "ModelSystemClass")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String modelSystemClass;
    @XmlAttribute(name = "VersionMajor")
    protected BigInteger versionMajor;
    @XmlAttribute(name = "VersionMinor")
    protected BigInteger versionMinor;
    @XmlAttribute(name = "VersionBuild")
    protected BigInteger versionBuild;
    @XmlAttribute(name = "VersionString")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String versionString;
    @XmlAttribute(name = "MfgDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar mfgDate;
    @XmlAttribute(name = "PatchLevel")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String patchLevel;
    @XmlAttribute(name = "DiscretePatches")
    @XmlSchemaType(name = "NMTOKENS")
    protected List<String> discretePatches;

    /**
     * Gets the value of the vendorID property.
     * 
     * @return
     *     possible object is
     *     {@link VendorIdType }
     *     
     */
    public VendorIdType getVendorID() {
        return vendorID;
    }

    /**
     * Sets the value of the vendorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorIdType }
     *     
     */
    public void setVendorID(VendorIdType value) {
        this.vendorID = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the simpleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimpleName() {
        return simpleName;
    }

    /**
     * Sets the value of the simpleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimpleName(String value) {
        this.simpleName = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the modelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelNumber() {
        return modelNumber;
    }

    /**
     * Sets the value of the modelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelNumber(String value) {
        this.modelNumber = value;
    }

    /**
     * Gets the value of the modelSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelSerialNumber() {
        return modelSerialNumber;
    }

    /**
     * Sets the value of the modelSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelSerialNumber(String value) {
        this.modelSerialNumber = value;
    }

    /**
     * Gets the value of the modelSystemClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelSystemClass() {
        return modelSystemClass;
    }

    /**
     * Sets the value of the modelSystemClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelSystemClass(String value) {
        this.modelSystemClass = value;
    }

    /**
     * Gets the value of the versionMajor property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionMajor() {
        return versionMajor;
    }

    /**
     * Sets the value of the versionMajor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionMajor(BigInteger value) {
        this.versionMajor = value;
    }

    /**
     * Gets the value of the versionMinor property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionMinor() {
        return versionMinor;
    }

    /**
     * Sets the value of the versionMinor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionMinor(BigInteger value) {
        this.versionMinor = value;
    }

    /**
     * Gets the value of the versionBuild property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionBuild() {
        return versionBuild;
    }

    /**
     * Sets the value of the versionBuild property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionBuild(BigInteger value) {
        this.versionBuild = value;
    }

    /**
     * Gets the value of the versionString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionString() {
        return versionString;
    }

    /**
     * Sets the value of the versionString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionString(String value) {
        this.versionString = value;
    }

    /**
     * Gets the value of the mfgDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMfgDate() {
        return mfgDate;
    }

    /**
     * Sets the value of the mfgDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMfgDate(XMLGregorianCalendar value) {
        this.mfgDate = value;
    }

    /**
     * Gets the value of the patchLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatchLevel() {
        return patchLevel;
    }

    /**
     * Sets the value of the patchLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatchLevel(String value) {
        this.patchLevel = value;
    }

    /**
     * Gets the value of the discretePatches property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discretePatches property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscretePatches().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDiscretePatches() {
        if (discretePatches == null) {
            discretePatches = new ArrayList<String>();
        }
        return this.discretePatches;
    }

}
