//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 03:47:01 PM EDT 
//


package gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.core_Integrity_v1_0_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HashedURIType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HashedURIType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="UriHash" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#}DigestValueType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="UriValue" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HashedURIType", propOrder = {
    "uriHash"
})
public class HashedURIType {

    @XmlElement(name = "UriHash")
    protected List<DigestValueType> uriHash;
    @XmlAttribute(name = "UriValue", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String uriValue;

    /**
     * Gets the value of the uriHash property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uriHash property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUriHash().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigestValueType }
     * 
     * 
     */
    public List<DigestValueType> getUriHash() {
        if (uriHash == null) {
            uriHash = new ArrayList<DigestValueType>();
        }
        return this.uriHash;
    }

    /**
     * Gets the value of the uriValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUriValue() {
        return uriValue;
    }

    /**
     * Sets the value of the uriValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUriValue(String value) {
        this.uriValue = value;
    }

}
