//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 03:47:01 PM EDT 
//


package gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.core_Integrity_v1_0_1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.integrity_Report_v1_0.SnapshotType;


/**
 * <p>Java class for IntegrityManifestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntegrityManifestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ComponentID" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#}ComponentIDType"/>
 *         &lt;element name="SignerInfo" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#}SignerInfoType" minOccurs="0"/>
 *         &lt;element name="ConfidenceValue" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#}ConfidenceValueType" minOccurs="0"/>
 *         &lt;element name="Collector" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#}ComponentRefType" minOccurs="0"/>
 *         &lt;element name="TransformMethod" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#}TransformMethodType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DigestMethod" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#}DigestMethodType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Values" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#}ValueType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AssertionInfo" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#}AssertionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PlatformClass" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#}PlatformClassType" minOccurs="0"/>
 *         &lt;element name="SubComponents" type="{http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#}ComponentRefType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="RevLevel" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntegrityManifestType", propOrder = {
    "componentID",
    "signerInfo",
    "confidenceValue",
    "collector",
    "transformMethod",
    "digestMethod",
    "values",
    "assertionInfo",
    "platformClass",
    "subComponents"
})
@XmlSeeAlso({
    SnapshotType.class
})
public abstract class IntegrityManifestType {

    @XmlElement(name = "ComponentID", required = true)
    protected ComponentIDType componentID;
    @XmlElement(name = "SignerInfo")
    protected SignerInfoType signerInfo;
    @XmlElement(name = "ConfidenceValue")
    protected ConfidenceValueType confidenceValue;
    @XmlElement(name = "Collector")
    protected ComponentRefType collector;
    @XmlElement(name = "TransformMethod")
    protected List<TransformMethodType> transformMethod;
    @XmlElement(name = "DigestMethod")
    protected List<DigestMethodType> digestMethod;
    @XmlElement(name = "Values")
    protected List<ValueType> values;
    @XmlElement(name = "AssertionInfo")
    protected List<AssertionType> assertionInfo;
    @XmlElement(name = "PlatformClass")
    protected PlatformClassType platformClass;
    @XmlElement(name = "SubComponents")
    protected List<ComponentRefType> subComponents;
    @XmlAttribute(name = "Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "RevLevel", required = true)
    protected BigInteger revLevel;

    /**
     * Gets the value of the componentID property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentIDType }
     *     
     */
    public ComponentIDType getComponentID() {
        return componentID;
    }

    /**
     * Sets the value of the componentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentIDType }
     *     
     */
    public void setComponentID(ComponentIDType value) {
        this.componentID = value;
    }

    /**
     * Gets the value of the signerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SignerInfoType }
     *     
     */
    public SignerInfoType getSignerInfo() {
        return signerInfo;
    }

    /**
     * Sets the value of the signerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignerInfoType }
     *     
     */
    public void setSignerInfo(SignerInfoType value) {
        this.signerInfo = value;
    }

    /**
     * Gets the value of the confidenceValue property.
     * 
     * @return
     *     possible object is
     *     {@link ConfidenceValueType }
     *     
     */
    public ConfidenceValueType getConfidenceValue() {
        return confidenceValue;
    }

    /**
     * Sets the value of the confidenceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfidenceValueType }
     *     
     */
    public void setConfidenceValue(ConfidenceValueType value) {
        this.confidenceValue = value;
    }

    /**
     * Gets the value of the collector property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentRefType }
     *     
     */
    public ComponentRefType getCollector() {
        return collector;
    }

    /**
     * Sets the value of the collector property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentRefType }
     *     
     */
    public void setCollector(ComponentRefType value) {
        this.collector = value;
    }

    /**
     * Gets the value of the transformMethod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transformMethod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransformMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransformMethodType }
     * 
     * 
     */
    public List<TransformMethodType> getTransformMethod() {
        if (transformMethod == null) {
            transformMethod = new ArrayList<TransformMethodType>();
        }
        return this.transformMethod;
    }

    /**
     * Gets the value of the digestMethod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the digestMethod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDigestMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigestMethodType }
     * 
     * 
     */
    public List<DigestMethodType> getDigestMethod() {
        if (digestMethod == null) {
            digestMethod = new ArrayList<DigestMethodType>();
        }
        return this.digestMethod;
    }

    /**
     * Gets the value of the values property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the values property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueType }
     * 
     * 
     */
    public List<ValueType> getValues() {
        if (values == null) {
            values = new ArrayList<ValueType>();
        }
        return this.values;
    }

    /**
     * Gets the value of the assertionInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assertionInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssertionInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssertionType }
     * 
     * 
     */
    public List<AssertionType> getAssertionInfo() {
        if (assertionInfo == null) {
            assertionInfo = new ArrayList<AssertionType>();
        }
        return this.assertionInfo;
    }

    /**
     * Gets the value of the platformClass property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformClassType }
     *     
     */
    public PlatformClassType getPlatformClass() {
        return platformClass;
    }

    /**
     * Sets the value of the platformClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformClassType }
     *     
     */
    public void setPlatformClass(PlatformClassType value) {
        this.platformClass = value;
    }

    /**
     * Gets the value of the subComponents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subComponents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubComponents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComponentRefType }
     * 
     * 
     */
    public List<ComponentRefType> getSubComponents() {
        if (subComponents == null) {
            subComponents = new ArrayList<ComponentRefType>();
        }
        return this.subComponents;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the revLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRevLevel() {
        return revLevel;
    }

    /**
     * Sets the value of the revLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRevLevel(BigInteger value) {
        this.revLevel = value;
    }

}
