//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 03:47:01 PM EDT 
//


package gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.core_Integrity_v1_0_1;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.core_Integrity_v1_0_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VendorIdTypeTcgVendorId_QNAME = new QName("http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#", "TcgVendorId");
    private final static QName _VendorIdTypeVendorGUID_QNAME = new QName("http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#", "VendorGUID");
    private final static QName _VendorIdTypeSmiVendorId_QNAME = new QName("http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#", "SmiVendorId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.core_Integrity_v1_0_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link PlatformClassType }
     * 
     */
    public PlatformClassType createPlatformClassType() {
        return new PlatformClassType();
    }

    /**
     * Create an instance of {@link VendorIdType }
     * 
     */
    public VendorIdType createVendorIdType() {
        return new VendorIdType();
    }

    /**
     * Create an instance of {@link ComponentIDType }
     * 
     */
    public ComponentIDType createComponentIDType() {
        return new ComponentIDType();
    }

    /**
     * Create an instance of {@link DigestValueType }
     * 
     */
    public DigestValueType createDigestValueType() {
        return new DigestValueType();
    }

    /**
     * Create an instance of {@link DigestMethodType }
     * 
     */
    public DigestMethodType createDigestMethodType() {
        return new DigestMethodType();
    }

    /**
     * Create an instance of {@link HashedURIType }
     * 
     */
    public HashedURIType createHashedURIType() {
        return new HashedURIType();
    }

    /**
     * Create an instance of {@link SignerInfoType }
     * 
     */
    public SignerInfoType createSignerInfoType() {
        return new SignerInfoType();
    }

    /**
     * Create an instance of {@link ComponentRefType.ComponentID }
     * 
     */
    public ComponentRefType.ComponentID createComponentRefTypeComponentID() {
        return new ComponentRefType.ComponentID();
    }

    /**
     * Create an instance of {@link HashType }
     * 
     */
    public HashType createHashType() {
        return new HashType();
    }

    /**
     * Create an instance of {@link AssertionType }
     * 
     */
    public AssertionType createAssertionType() {
        return new AssertionType();
    }

    /**
     * Create an instance of {@link ConfidenceValueType }
     * 
     */
    public ConfidenceValueType createConfidenceValueType() {
        return new ConfidenceValueType();
    }

    /**
     * Create an instance of {@link TransformMethodType }
     * 
     */
    public TransformMethodType createTransformMethodType() {
        return new TransformMethodType();
    }

    /**
     * Create an instance of {@link ComponentRefType }
     * 
     */
    public ComponentRefType createComponentRefType() {
        return new ComponentRefType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#", name = "TcgVendorId", scope = VendorIdType.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createVendorIdTypeTcgVendorId(String value) {
        return new JAXBElement<String>(_VendorIdTypeTcgVendorId_QNAME, String.class, VendorIdType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#", name = "VendorGUID", scope = VendorIdType.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVendorIdTypeVendorGUID(String value) {
        return new JAXBElement<String>(_VendorIdTypeVendorGUID_QNAME, String.class, VendorIdType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#", name = "SmiVendorId", scope = VendorIdType.class)
    public JAXBElement<BigInteger> createVendorIdTypeSmiVendorId(BigInteger value) {
        return new JAXBElement<BigInteger>(_VendorIdTypeSmiVendorId_QNAME, BigInteger.class, VendorIdType.class, value);
    }

}
