//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 03:47:01 PM EDT 
//


package gov.niarl.his.xsd.integrity_Report_v1_0.org.trustedcomputinggroup.xml.schema.core_Integrity_v1_0_1;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for VendorIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VendorIdType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="TcgVendorId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SmiVendorId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="VendorGUID" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN"/>
 *       &lt;/choice>
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VendorIdType", propOrder = {
    "tcgVendorIdOrSmiVendorIdOrVendorGUID"
})
public class VendorIdType {

    @XmlElementRefs({
        @XmlElementRef(name = "VendorGUID", namespace = "http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#", type = JAXBElement.class),
        @XmlElementRef(name = "SmiVendorId", namespace = "http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#", type = JAXBElement.class),
        @XmlElementRef(name = "TcgVendorId", namespace = "http://www.trustedcomputinggroup.org/XML/SCHEMA/Core_Integrity_v1_0_1#", type = JAXBElement.class)
    })
    protected List<JAXBElement<? extends Serializable>> tcgVendorIdOrSmiVendorIdOrVendorGUID;
    @XmlAttribute(name = "Name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String name;

    /**
     * Gets the value of the tcgVendorIdOrSmiVendorIdOrVendorGUID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tcgVendorIdOrSmiVendorIdOrVendorGUID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTcgVendorIdOrSmiVendorIdOrVendorGUID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Serializable>> getTcgVendorIdOrSmiVendorIdOrVendorGUID() {
        if (tcgVendorIdOrSmiVendorIdOrVendorGUID == null) {
            tcgVendorIdOrSmiVendorIdOrVendorGUID = new ArrayList<JAXBElement<? extends Serializable>>();
        }
        return this.tcgVendorIdOrSmiVendorIdOrVendorGUID;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
